### ISSUE TITLE
Can't load pages without errors

### ISSUE THREAD

**Issue by krugertech** [PayGate/sample-code-csharp#4]
I'm running Visual Studio 2017.

For whatever reason, the nuget packages are not not restored for this project resulting in errors due to missing assemblies in the bin folder.

To resolve this, uninstall each nuget package in the packages.config and re-install them to get this website working.

**Comment by RBAtkins0n** [comment]
Thanks @krugertech, will investigate and resolve.

**Comment by RBAtkins0n** [comment]
Hi @krugertech 
Does #5 fix the issue?
