### ISSUE TITLE
Paygate ID length validation

### ISSUE THREAD

**Issue by krugertech** [PayGate/sample-code-csharp#6]
Greetings, 

Please see:
>> /sample-code-csharp/WebSite1/PayWeb3/request.cshtml
>> line 17

Client PayGate-ID's can now be 13 characters long and will fail validation in this demo. 

Suggested fix:
`{"PAYGATE_ID", Regex.IsMatch(Request["PAYGATE_ID"], @"^\d{9,13}$") ? Request["PAYGATE_ID"] : "INVALID ID" },`

**Comment by RBAtkins0n** [comment]
Closed in #7
